import type { MetricItem } from "@/shared/types/site";
import { TABLECOR_ALL_FAMILY_LABEL } from "@/features/tablecor/tablecor.constants";

export const tablecorMetrics: MetricItem[] = [
  { value: "240+", label: "Decorados curados para mobiliario y paneleria interior" },
  { value: "0.3 mm", label: "Tolerancia objetivo para corte, canteo y perforado" },
  { value: "4 lineas", label: "Seccionado, nesting CNC, canteo premium y drilling" },
  { value: "72 h", label: "Ventana sugerida para activar muestra y propuesta tecnica" },
];

export const tablecorFamilies = [
  TABLECOR_ALL_FAMILY_LABEL,
  "Maderas",
  "Piedras",
  "Solidos",
  "Textiles",
] as const;

export const tablecorSurfaces = [
  {
    id: "nogal-faro",
    code: "TC-421",
    name: "Nogal Faro",
    family: "Maderas",
    finish: "Poro sincronizado",
    thickness: "18 mm",
    base: "#745640",
    accent: "#ba8f6d",
    glow: "#ead0b7",
    applications: ["Cocinas", "Recepciones", "Muebles de autor"],
    note: "Veta larga y elegante para frentes completos, torres y paneles con lectura sobria.",
  },
  {
    id: "roble-siena",
    code: "TC-390",
    name: "Roble Siena",
    family: "Maderas",
    finish: "Mate natural",
    thickness: "15 mm",
    base: "#9c7a5e",
    accent: "#d2ae8f",
    glow: "#f1dcc7",
    applications: ["Dormitorios", "Home office", "Retail ligero"],
    note: "Una madera media para mobiliario residencial con tono calido y luz controlada.",
  },
  {
    id: "cedro-aureo",
    code: "TC-438",
    name: "Cedro Aureo",
    family: "Maderas",
    finish: "Cepillado fino",
    thickness: "18 mm",
    base: "#8f5d3d",
    accent: "#ce9368",
    glow: "#f4d6bb",
    applications: ["Hospitality", "Wall cladding", "Muebles bar"],
    note: "Madera cobriza para paneles verticales, barras y modulos de alto impacto visual.",
  },
  {
    id: "travertino-duna",
    code: "TC-118",
    name: "Travertino Duna",
    family: "Piedras",
    finish: "Textura mineral",
    thickness: "18 mm",
    base: "#cbc0b1",
    accent: "#ede3d4",
    glow: "#faf3ea",
    applications: ["Islas", "Wall panels", "Showrooms"],
    note: "Mineral claro para barras, cubiertas verticales y paneles de lectura arquitectonica.",
  },
  {
    id: "basalto-grafito",
    code: "TC-102",
    name: "Basalto Grafito",
    family: "Piedras",
    finish: "Soft touch",
    thickness: "18 mm",
    base: "#343a42",
    accent: "#6d7580",
    glow: "#adb8c5",
    applications: ["Oficinas", "Retail premium", "Mobiliario oscuro"],
    note: "Grafito profundo para modulos ejecutivos, vitrinas y frentes de gran presencia.",
  },
  {
    id: "arcilla-plena",
    code: "TC-215",
    name: "Arcilla Plena",
    family: "Solidos",
    finish: "Supermate",
    thickness: "18 mm",
    base: "#b26f4a",
    accent: "#ddb08f",
    glow: "#f7d8c1",
    applications: ["Muebles bajos", "Paneles", "Acentos interiores"],
    note: "Solido terroso de tacto controlado para composiciones con piedra y madera media.",
  },
  {
    id: "marfil-calma",
    code: "TC-244",
    name: "Marfil Calma",
    family: "Solidos",
    finish: "Supermate anti-huella",
    thickness: "18 mm",
    base: "#d7ccbb",
    accent: "#f1e8db",
    glow: "#fff8f0",
    applications: ["Closets", "Dormitorios", "Paneles lisos"],
    note: "Marfil quieto para proyectos donde el volumen debe leerse limpio y continuo.",
  },
  {
    id: "lino-humo",
    code: "TC-307",
    name: "Lino Humo",
    family: "Textiles",
    finish: "Textura fina",
    thickness: "15 mm",
    base: "#61615e",
    accent: "#9d9b94",
    glow: "#d8d4cb",
    applications: ["Back panels", "Showrooms", "Home office"],
    note: "Textil gris neutro para fondos, repisas y piezas de composicion silenciosa.",
  },
  {
    id: "lino-avena",
    code: "TC-312",
    name: "Lino Avena",
    family: "Textiles",
    finish: "Textura tejida",
    thickness: "15 mm",
    base: "#b8ab97",
    accent: "#e5d7c4",
    glow: "#faf0e4",
    applications: ["Vestidores", "Hoteleria", "Puntos de venta"],
    note: "Textil claro para interiores suaves donde la superficie debe sentirse mas tactil.",
  },
] as const;

export const tablecorPrograms = [
  {
    id: "atelier-kitchen",
    title: "Kitchen Atelier",
    sector: "Residencial premium",
    summary:
      "Programa de cocina con isla escultorica, torres completas y un mueble bar integrado en la misma paleta.",
    highlight: "Lote pensado para frentes continuos, vetas alineadas y herrajes ocultos.",
    furniture: ["Isla central", "Torres de hornos", "Mueble bar", "Panel trasero iluminado"],
    blend: ["Nogal Faro", "Travertino Duna", "Arcilla Plena"],
    surfaceIds: ["nogal-faro", "travertino-duna", "arcilla-plena"],
    machineIds: ["beam-saw", "nesting-cnc", "edge-laser"],
    cutPlanId: "kitchen-batch",
    stats: [
      { label: "Modulos", value: "12" },
      { label: "Tableros", value: "28" },
      { label: "Tiempo de linea", value: "43 min" },
    ],
    photo: "/images/tablecor/kitchen-premium.jpg",
    photoAlt: "Cocina premium con mobiliario de madera, isla y electrodomesticos integrados.",
    photoNote: "Frentes continuos, isla protagonista y lectura calida de madera premium.",
    base: "#5e4739",
    accent: "#d3b394",
    glow: "#f6e2d1",
  },
  {
    id: "wardrobe-suite",
    title: "Wardrobe Suite",
    sector: "Closets y vestidores",
    summary:
      "Sistema de vestidor con nichos, frentes lisos y respaldo textil para dar orden visual sin perder calidez.",
    highlight: "Volumen claro, repetible y muy eficiente para series de dormitorio de alto valor.",
    furniture: ["Torres de ropa", "Cajoneras", "Zapateras", "Panel de tocador"],
    blend: ["Marfil Calma", "Roble Siena", "Lino Avena"],
    surfaceIds: ["marfil-calma", "roble-siena", "lino-avena"],
    machineIds: ["beam-saw", "drill-cell", "edge-laser"],
    cutPlanId: "wardrobe-grid",
    stats: [
      { label: "Modulos", value: "18" },
      { label: "Piezas", value: "74" },
      { label: "Tiempo de linea", value: "51 min" },
    ],
    photo: "/images/tablecor/walkin-closet.jpg",
    photoAlt: "Walk-in closet de madera clara con repisas, cajoneras y paneles integrados.",
    photoNote: "Vestidor modular con paneleria clara, nichos amplios y carpinteria de precision.",
    base: "#d8cebe",
    accent: "#f2e4d1",
    glow: "#fff8ee",
  },
  {
    id: "retail-lab",
    title: "Retail Lab",
    sector: "Showrooms y hospitality",
    summary:
      "Programa de paneleria, counters y exhibidores para espacios comerciales con alto trafico y acabado controlado.",
    highlight: "Pensado para paneles verticales, frentes oscuros y secuencias rapidas de reposicion.",
    furniture: ["Counter frontal", "Panel muro", "Exhibidor central", "Modulo de caja"],
    blend: ["Cedro Aureo", "Basalto Grafito", "Lino Humo"],
    surfaceIds: ["cedro-aureo", "basalto-grafito", "lino-humo"],
    machineIds: ["nesting-cnc", "edge-laser", "drill-cell"],
    cutPlanId: "retail-wall",
    stats: [
      { label: "Modulos", value: "9" },
      { label: "Paneles", value: "36" },
      { label: "Tiempo de linea", value: "39 min" },
    ],
    photo: "/images/tablecor/hospitality-lobby.jpg",
    photoAlt: "Lobby hospitality con paneleria, carpinteria vertical e iluminacion premium.",
    photoNote: "Paneles y mobiliario para hospitality donde la superficie ordena toda la atmosfera.",
    base: "#352d2b",
    accent: "#b57654",
    glow: "#f0c9ae",
  },
] as const;

export const tablecorProcessSteps = [
  {
    id: "brief",
    order: "01",
    title: "Brief tecnico",
    copy: "Se define programa, materialidad, espesor, sentido de veta y lote comercial.",
    signal: "Input comercial y planos de base",
  },
  {
    id: "optimization",
    order: "02",
    title: "Optimizacion",
    copy: "El tablero se despieza con criterio de veta, repeticion y merma permitida.",
    signal: "Nesting y orden de corte",
  },
  {
    id: "cut",
    order: "03",
    title: "Corte primario",
    copy: "La linea beam saw o CNC parte el tablero y etiqueta cada pieza para el lote.",
    signal: "Secuencia, tolerancia y trazabilidad",
  },
  {
    id: "edge",
    order: "04",
    title: "Canteo premium",
    copy: "Se estabiliza el borde con adhesivo controlado, presion estable y acabado limpio.",
    signal: "Frentes listos para armado",
  },
  {
    id: "drill",
    order: "05",
    title: "Perforado y herrajes",
    copy: "Cada pieza pasa por drilling para asegurar repeticion de uniones y hardware oculto.",
    signal: "Piezas listas para montaje",
  },
  {
    id: "quality",
    order: "06",
    title: "Control final",
    copy: "El lote se revisa por tono, canteo, continuidad de veta y empaquetado por programa.",
    signal: "Liberacion comercial",
  },
] as const;

export const tablecorCutPlans = [
  {
    id: "kitchen-batch",
    title: "Plan de corte / isla + torres",
    programId: "atelier-kitchen",
    boardSize: "2440 x 1830 mm",
    yield: "92%",
    scrap: "8%",
    machine: "Seccionadora + nesting",
    cadence: "43 min",
    notes: [
      "Frentes principales con veta alineada en toda la isla.",
      "Las piezas espejo se separan en el mismo lote para evitar variacion.",
      "El sobrante util se reserva para bandejas y fondos interiores.",
    ],
    pieces: [
      { id: "k1", label: "Isla lateral", x: 4, y: 7, w: 20, h: 44, tone: "base" },
      { id: "k2", label: "Isla lateral", x: 26, y: 7, w: 20, h: 44, tone: "base" },
      { id: "k3", label: "Frente cajon", x: 48, y: 7, w: 18, h: 19, tone: "accent" },
      { id: "k4", label: "Frente cajon", x: 68, y: 7, w: 18, h: 19, tone: "accent" },
      { id: "k5", label: "Cubierta visual", x: 48, y: 29, w: 38, h: 22, tone: "glow" },
      { id: "k6", label: "Torre horno", x: 4, y: 54, w: 26, h: 34, tone: "accent" },
      { id: "k7", label: "Bar panel", x: 32, y: 54, w: 26, h: 34, tone: "base" },
      { id: "k8", label: "Fondo modulo", x: 60, y: 54, w: 26, h: 20, tone: "glow" },
      { id: "k9", label: "Repisas", x: 60, y: 76, w: 26, h: 12, tone: "accent" },
    ],
  },
  {
    id: "wardrobe-grid",
    title: "Plan de corte / vestidor modular",
    programId: "wardrobe-suite",
    boardSize: "2750 x 1830 mm",
    yield: "89%",
    scrap: "11%",
    machine: "Beam saw + drill cell",
    cadence: "51 min",
    notes: [
      "Las costillas verticales se cortan primero para asegurar repeticion visual.",
      "Los fondos textiles quedan agrupados para reducir cambios de programa.",
      "El sobrante recto alimenta cajones interiores y tapas de accesorios.",
    ],
    pieces: [
      { id: "w1", label: "Costado A", x: 4, y: 8, w: 18, h: 58, tone: "glow" },
      { id: "w2", label: "Costado B", x: 24, y: 8, w: 18, h: 58, tone: "glow" },
      { id: "w3", label: "Puerta 1", x: 44, y: 8, w: 16, h: 58, tone: "base" },
      { id: "w4", label: "Puerta 2", x: 62, y: 8, w: 16, h: 58, tone: "base" },
      { id: "w5", label: "Cajonera", x: 80, y: 8, w: 14, h: 26, tone: "accent" },
      { id: "w6", label: "Repisas", x: 80, y: 38, w: 14, h: 28, tone: "accent" },
      { id: "w7", label: "Zapatero", x: 4, y: 70, w: 28, h: 18, tone: "accent" },
      { id: "w8", label: "Tocador", x: 34, y: 70, w: 28, h: 18, tone: "base" },
      { id: "w9", label: "Fondo textil", x: 64, y: 70, w: 30, h: 18, tone: "glow" },
    ],
  },
  {
    id: "retail-wall",
    title: "Plan de corte / counter + wall panel",
    programId: "retail-lab",
    boardSize: "2440 x 1830 mm",
    yield: "94%",
    scrap: "6%",
    machine: "Nesting CNC + edge laser",
    cadence: "39 min",
    notes: [
      "Los paneles verticales viajan en nesting para conservar patron y perforaciones.",
      "El grafito profundo se reserva para frentes y zocalos de alto desgaste.",
      "La merma baja porque el lote prioriza paneles rectangulares de gran formato.",
    ],
    pieces: [
      { id: "r1", label: "Panel muro", x: 4, y: 7, w: 26, h: 56, tone: "base" },
      { id: "r2", label: "Panel muro", x: 32, y: 7, w: 26, h: 56, tone: "base" },
      { id: "r3", label: "Counter frente", x: 60, y: 7, w: 34, h: 26, tone: "accent" },
      { id: "r4", label: "Counter tapa", x: 60, y: 35, w: 34, h: 14, tone: "glow" },
      { id: "r5", label: "Caja lateral", x: 60, y: 51, w: 16, h: 12, tone: "accent" },
      { id: "r6", label: "Caja lateral", x: 78, y: 51, w: 16, h: 12, tone: "accent" },
      { id: "r7", label: "Exhibidor", x: 4, y: 67, w: 28, h: 19, tone: "glow" },
      { id: "r8", label: "Base modulo", x: 34, y: 67, w: 28, h: 19, tone: "base" },
      { id: "r9", label: "Frente modulo", x: 64, y: 67, w: 30, h: 19, tone: "accent" },
    ],
  },
] as const;

export const tablecorMachines = [
  {
    id: "beam-saw",
    name: "Seccionadora orbital",
    stage: "Corte primario",
    copy:
      "Pensada para lotes repetibles con empuje servo, control de veta y etiqueta por pieza en la misma pasada.",
    bestFor: "Series de cocina, closets y paneleria recta",
    shiftOutput: "96 piezas / turno",
    precision: "+/- 0.15 mm",
    efficiency: 92,
    tech: ["Etiquetado inline", "Empuje servo", "Optimiza veta"],
    photo: "/images/tablecor/sliding-saw.jpg",
    photoAlt: "Operario usando una seccionadora o sierra deslizante para cortar paneles de madera.",
    photoNote: "Corte lineal para tableros rectos, lotes repetibles y arranque rapido de produccion.",
    base: "#403734",
    accent: "#c47b57",
    glow: "#f2c7a7",
  },
  {
    id: "nesting-cnc",
    name: "Nesting CNC 5 ejes",
    stage: "Corte de geometria libre",
    copy:
      "Resuelve paneles con vaciados, perforacion combinada y secuencias de muebles mas complejos en un solo tablero.",
    bestFor: "Counters, paneles especiales y exhibidores",
    shiftOutput: "18 tableros / turno",
    precision: "+/- 0.10 mm",
    efficiency: 88,
    tech: ["Tool changer", "Vacio zonificado", "Despiece especial"],
    photo: "/images/tablecor/cnc-router.jpg",
    photoAlt: "Operario junto a una maquina CNC router realizando corte de madera con precision.",
    photoNote: "Ideal para nesting, geometria libre y piezas con vaciados o perforacion combinada.",
    base: "#2f3943",
    accent: "#7ea4c6",
    glow: "#c4ddf5",
  },
  {
    id: "edge-laser",
    name: "Enchapadora laser",
    stage: "Canteo premium",
    copy:
      "Linea de borde para piezas visibles con union mas limpia, presion estable y lectura continua del frente.",
    bestFor: "Frentes premium y volumenes de alto contacto",
    shiftOutput: "420 ml / turno",
    precision: "Union casi invisible",
    efficiency: 94,
    tech: ["Laser edge", "Pulido dual", "Radio premium"],
    photo: "/images/tablecor/edge-bander.jpg",
    photoAlt: "Enchapadora de cantos procesando un tablero de madera con borde visible y acabado premium.",
    photoNote: "Canteo premium para frentes visibles, union limpia y continuidad mas controlada del mueble.",
    base: "#433226",
    accent: "#de9f63",
    glow: "#ffd9af",
  },
  {
    id: "drill-cell",
    name: "Drilling cell",
    stage: "Perforado y herrajes",
    copy:
      "Celda automatizada para uniones, tarugos y hardware oculto con repeticion estable por programa.",
    bestFor: "Closets, cajoneras y modulos seriados",
    shiftOutput: "180 piezas / turno",
    precision: "Patron continuo",
    efficiency: 90,
    tech: ["Multi spindle", "Lectura por lote", "Herraje oculto"],
    photo: "/images/tablecor/drill-cell.jpg",
    photoAlt: "Detalle de perforado industrial en una celda de mecanizado para piezas de mobiliario.",
    photoNote: "Perforado repetible para herrajes, uniones ocultas y armado rapido de modulos.",
    base: "#31413f",
    accent: "#83b4a6",
    glow: "#cce8dd",
  },
] as const;

export const tablecorProductionModes = [
  {
    id: "pilot",
    label: "Piloto 1 lote",
    leadTime: "48-72 h",
    throughputFactor: 0.76,
    scrapDelta: 2,
    commercialOutput: "Muestra, propuesta tecnica y lote de validacion",
  },
  {
    id: "series",
    label: "Serie comercial",
    leadTime: "5-7 dias",
    throughputFactor: 1,
    scrapDelta: 0,
    commercialOutput: "Paquete completo para produccion repetible",
  },
  {
    id: "rush",
    label: "Entrega express",
    leadTime: "24-48 h",
    throughputFactor: 1.18,
    scrapDelta: 1,
    commercialOutput: "Respuesta priorizada para obra o montaje urgente",
  },
] as const;

export const tablecorSpecs = [
  { label: "Tablero madre", value: "2440 x 1830 y 2750 x 1830 mm" },
  { label: "Espesores", value: "15 mm, 18 mm y 25 mm segun programa" },
  { label: "Acabados", value: "Poro, supermate, soft touch, mineral y textil" },
  { label: "Salida comercial", value: "Muestra A4, 30 x 30, tablero full y ficha tecnica" },
] as const;

export const tablecorServiceSteps = [
  {
    title: "Curaduria de paleta",
    copy: "El equipo aterriza un blend util de tableros, tonos y espesores segun tipo de mueble.",
  },
  {
    title: "Definicion de lote",
    copy: "Se conecta el programa comercial con el plan de corte y la linea de maquinaria sugerida.",
  },
  {
    title: "Salida comercial",
    copy: "La respuesta puede salir como muestra fisica, plan de corte o paquete tecnico para cotizacion.",
  },
] as const;

export const sampleFormats = [
  "A4 inspiracional",
  "Muestra 30 x 30",
  "Tablero full",
  "Kit de paleta completa",
] as const;

export const projectSpeeds = [
  "Salida estandar",
  "Curaduria rapida",
  "Desarrollo premium",
] as const;
